// Copyright 2026 Chris Wells <chris@rhza.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package archivedb

import (
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// Run represents a row in the runs table.
type Run struct {
	ID          string
	PixeVersion string
	Source      string
	Destination string
	Algorithm   string
	Workers     int
	Recursive   bool
	StartedAt   time.Time
	FinishedAt  *time.Time
	Status      string // "running", "completed", "interrupted"
}

// boolToInt converts a bool to 0/1 for SQLite INTEGER storage.
func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

// InsertRun creates a new run record with status "running".
// The ID should be a UUID v4 generated by the caller.
func (db *DB) InsertRun(r *Run) error {
	const q = `
		INSERT INTO runs (id, pixe_version, source, destination, algorithm, workers, recursive, started_at, status)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'running')`

	_, err := db.conn.Exec(q,
		r.ID,
		r.PixeVersion,
		r.Source,
		r.Destination,
		r.Algorithm,
		r.Workers,
		boolToInt(r.Recursive),
		r.StartedAt.UTC().Format(time.RFC3339),
	)
	if err != nil {
		return fmt.Errorf("archivedb: insert run: %w", err)
	}
	return nil
}

// CompleteRun sets the run's status to "completed" and records finished_at.
func (db *DB) CompleteRun(runID string, finishedAt time.Time) error {
	return db.finishRun(runID, "completed", finishedAt)
}

// InterruptRun sets the run's status to "interrupted" and records finished_at.
func (db *DB) InterruptRun(runID string, finishedAt time.Time) error {
	return db.finishRun(runID, "interrupted", finishedAt)
}

// finishRun is the shared implementation for CompleteRun and InterruptRun.
func (db *DB) finishRun(runID, status string, finishedAt time.Time) error {
	const q = `UPDATE runs SET status = ?, finished_at = ? WHERE id = ?`
	res, err := db.conn.Exec(q, status, finishedAt.UTC().Format(time.RFC3339), runID)
	if err != nil {
		return fmt.Errorf("archivedb: finish run (%s): %w", status, err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("archivedb: finish run rows affected: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("archivedb: finish run: run %q not found", runID)
	}
	return nil
}

// GetRun retrieves a run by ID. Returns (nil, nil) if not found.
func (db *DB) GetRun(runID string) (*Run, error) {
	const q = `
		SELECT id, pixe_version, source, destination, algorithm, workers, recursive,
		       started_at, finished_at, status
		FROM runs WHERE id = ?`

	row := db.conn.QueryRow(q, runID)
	return scanRun(row)
}

// FindInterruptedRuns returns all runs with status "running" (i.e., interrupted
// by a prior crash or signal), ordered by started_at descending.
func (db *DB) FindInterruptedRuns() ([]*Run, error) {
	const q = `
		SELECT id, pixe_version, source, destination, algorithm, workers, recursive,
		       started_at, finished_at, status
		FROM runs WHERE status = 'running'
		ORDER BY started_at DESC`

	rows, err := db.conn.Query(q)
	if err != nil {
		return nil, fmt.Errorf("archivedb: find interrupted runs: %w", err)
	}
	defer func() { _ = rows.Close() }()

	var runs []*Run
	for rows.Next() {
		r, err := scanRun(rows)
		if err != nil {
			return nil, err
		}
		runs = append(runs, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("archivedb: find interrupted runs iterate: %w", err)
	}
	return runs, nil
}

// scanner is satisfied by both *sql.Row and *sql.Rows.
type scanner interface {
	Scan(dest ...any) error
}

// scanRun reads a Run from a row scanner. Returns (nil, nil) on sql.ErrNoRows.
func scanRun(s scanner) (*Run, error) {
	var r Run
	var startedAtStr string
	var finishedAtStr sql.NullString
	var recursiveInt int

	err := s.Scan(
		&r.ID,
		&r.PixeVersion,
		&r.Source,
		&r.Destination,
		&r.Algorithm,
		&r.Workers,
		&recursiveInt,
		&startedAtStr,
		&finishedAtStr,
		&r.Status,
	)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("archivedb: scan run: %w", err)
	}

	r.Recursive = recursiveInt != 0

	r.StartedAt, err = time.Parse(time.RFC3339, startedAtStr)
	if err != nil {
		return nil, fmt.Errorf("archivedb: parse run started_at: %w", err)
	}

	if finishedAtStr.Valid {
		t, err := time.Parse(time.RFC3339, finishedAtStr.String)
		if err != nil {
			return nil, fmt.Errorf("archivedb: parse run finished_at: %w", err)
		}
		r.FinishedAt = &t
	}

	return &r, nil
}
