// Copyright 2026 Chris Wells <chris@rhza.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package pipeline implements the sort orchestrator that wires together
// discovery, extraction, hashing, path building, copy, verify, tagging,
// and archive-DB / ledger persistence.
//
// State is persisted to the SQLite archive database (archivedb). The ledger
// (dirA/.pixe_ledger.json) is written in JSONL format via manifest.LedgerWriter:
// the coordinator goroutine streams one JSON line per file as each result is
// finalised, keeping memory usage O(1) regardless of file count.
package pipeline

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mattn/go-isatty"

	"github.com/cwlls/pixe/internal/archivedb"
	"github.com/cwlls/pixe/internal/config"
	copypkg "github.com/cwlls/pixe/internal/copy"
	"github.com/cwlls/pixe/internal/discovery"
	"github.com/cwlls/pixe/internal/domain"
	"github.com/cwlls/pixe/internal/hash"
	"github.com/cwlls/pixe/internal/ignore"
	"github.com/cwlls/pixe/internal/manifest"
	"github.com/cwlls/pixe/internal/pathbuilder"
	"github.com/cwlls/pixe/internal/progress"
	"github.com/cwlls/pixe/internal/tagging"
)

// SortOptions holds the resolved runtime options for a sort run.
// It is constructed by the CLI layer and passed into Run.
type SortOptions struct {
	// Config is the resolved application configuration.
	Config *config.AppConfig
	// Hasher computes content checksums for deduplication and verification.
	Hasher *hash.Hasher
	// Registry maps file extensions to their FileTypeHandler implementations.
	Registry *discovery.Registry
	// RunTimestamp is the formatted timestamp for this run, used in duplicate directory naming (e.g., "20260306_103000").
	RunTimestamp string
	// Output is where progress lines are written. Defaults to os.Stdout.
	Output io.Writer
	// PixeVersion is the version string stamped into ledgers.
	// Set by the CLI layer via cmd.Version() to avoid an import cycle.
	PixeVersion string
	// DB is the open archive database. Required for all non-dry-run operations.
	DB *archivedb.DB
	// RunID is the UUID for this run, pre-generated by the caller.
	RunID string
	// EventBus, when non-nil, receives structured progress events alongside
	// the plain-text Output writer. Both can be active simultaneously.
	// When nil, no events are emitted (existing behaviour is unchanged).
	EventBus *progress.Bus
	// ColorOutput, when true, enables ANSI color codes in status verb output.
	// Automatically set by the CLI layer based on TTY detection and NO_COLOR.
	ColorOutput bool
	// PathTemplate controls the directory structure for destination paths.
	// When nil, the default template ("{year}/{month}-{monthname}") is used.
	PathTemplate *pathbuilder.Template
	// Context, when non-nil, is used for graceful cancellation (e.g. SIGINT).
	// Workers finish their current file before exiting. When nil,
	// context.Background() is used (no cancellation).
	Context context.Context

	// DestLabel is the display prefix for destination paths in stdout output
	// (e.g. "...Photos"). Set by the CLI layer to "..." + filepath.Base(dest).
	// When empty, relDest is shown without a prefix. This is purely cosmetic —
	// it does not affect the ledger, database, or filesystem paths.
	DestLabel string

	// Yes, when true, suppresses interactive prompts and auto-accepts them.
	// Equivalent to the --yes / -y CLI flag.
	Yes bool

	// NoLedger, when true, explicitly opts out of ledger creation without
	// prompting or warning. Equivalent to the --no-ledger CLI flag.
	NoLedger bool
}

// emit sends an event to the bus if one is configured. It is a no-op when
// bus is nil, so callers do not need to guard every call site.
func emit(bus *progress.Bus, e progress.Event) {
	if bus != nil {
		bus.Emit(e)
	}
}

// displayDest returns relDest formatted for human-readable stdout output.
// When destLabel is non-empty (e.g. "...Photos"), it is prepended with a "/"
// separator so the output reads "...Photos/2021/12-Dec/filename.jpg".
// When destLabel is empty, relDest is returned unchanged.
func displayDest(destLabel, relDest string) string {
	if destLabel == "" {
		return relDest
	}
	return destLabel + "/" + relDest
}

// dateFilterSkip is returned by processFile when a file is skipped due to
// the --since/--before date filter. It is not an error — the caller should
// treat it as a skip.
type dateFilterSkip struct {
	reason      string
	captureDate time.Time
}

func (d *dateFilterSkip) Error() string { return d.reason }

// SortResult summarises the outcome of a completed sort run.
type SortResult struct {
	Processed  int // Processed is the total number of files that completed the pipeline.
	Duplicates int // Duplicates is the number of files identified as content duplicates.
	Skipped    int // Skipped is the number of files skipped (previously imported or unsupported).
	Errors     int // Errors is the number of files that failed at some pipeline stage.
}

// Run executes the full sort pipeline, selecting sequential or concurrent
// execution based on opts.Config.Workers.
//
// Pipeline per file:
//
//	discover → extract date → hash payload → dedup check → build path
//	→ copy → verify → tag (optional) → update DB → update ledger
//
// After all files: write ledger to dirA, mark run complete in DB.
// In dry-run mode the copy/verify/tag steps are skipped; everything else runs.
//
// Cancellation: if opts.Context is cancelled (e.g. via SIGINT), the pipeline
// stops accepting new files, drains in-flight work, and returns gracefully.
func Run(opts SortOptions) (SortResult, error) {
	// Resolve context — default to Background when the caller did not provide one.
	ctx := opts.Context
	if ctx == nil {
		ctx = context.Background()
	}

	out := opts.Output
	if out == nil {
		out = os.Stdout
	}

	cfg := opts.Config
	dirA := cfg.Source
	dirB := cfg.Destination
	db := opts.DB

	startedAt := time.Now().UTC()

	// ------------------------------------------------------------------
	// 1. Register this run in the archive DB.
	// ------------------------------------------------------------------
	run := &archivedb.Run{
		ID:          opts.RunID,
		PixeVersion: opts.PixeVersion,
		Source:      dirA,
		Destination: dirB,
		Algorithm:   opts.Hasher.Algorithm(),
		Workers:     cfg.Workers,
		Recursive:   cfg.Recursive,
		StartedAt:   startedAt,
	}
	if db != nil {
		if err := db.InsertRun(run); err != nil {
			return SortResult{}, fmt.Errorf("pipeline: insert run: %w", err)
		}
	}

	// ------------------------------------------------------------------
	// 2. Walk dirA.
	// ------------------------------------------------------------------
	emit(opts.EventBus, progress.Event{Kind: progress.EventDiscoverStart})
	walkOpts := discovery.WalkOptions{
		Recursive:     cfg.Recursive,
		Ignore:        ignore.New(cfg.Ignore),
		CarrySidecars: cfg.CarrySidecars,
	}
	discovered, skipped, err := discovery.Walk(dirA, opts.Registry, walkOpts)
	if err != nil {
		return SortResult{}, fmt.Errorf("pipeline: walk source: %w", err)
	}
	emit(opts.EventBus, progress.Event{
		Kind:    progress.EventDiscoverDone,
		Total:   len(discovered),
		Skipped: len(skipped),
	})

	// ------------------------------------------------------------------
	// 3. Batch-insert all discovered files as "pending".
	// ------------------------------------------------------------------
	// fileIDs maps source path → DB file ID.
	fileIDs := make(map[string]int64, len(discovered))
	if db != nil && len(discovered) > 0 {
		records := make([]*archivedb.FileRecord, len(discovered))
		for i, df := range discovered {
			records[i] = &archivedb.FileRecord{
				RunID:      opts.RunID,
				SourcePath: df.Path,
			}
		}
		ids, err := db.InsertFiles(records)
		if err != nil {
			return SortResult{}, fmt.Errorf("pipeline: batch insert files: %w", err)
		}
		for i, df := range discovered {
			fileIDs[df.Path] = ids[i]
		}
	}

	// ------------------------------------------------------------------
	// 4. Open streaming ledger writer (nil in dry-run — no ledger written).
	// ------------------------------------------------------------------
	var slw *manifest.SafeLedgerWriter
	if !cfg.DryRun {
		header := domain.LedgerHeader{
			Version:     5,
			RunID:       opts.RunID,
			PixeVersion: opts.PixeVersion,
			PixeRun:     startedAt.UTC().Format(time.RFC3339),
			Algorithm:   opts.Hasher.Algorithm(),
			Destination: dirB,
			Recursive:   cfg.Recursive,
		}
		rawLW, lwErr := manifest.NewLedgerWriter(dirA, header)
		if lwErr != nil {
			cancelled, promptErr := handleLedgerFailure(out, dirA, lwErr, opts.Yes, opts.NoLedger)
			if promptErr != nil {
				return SortResult{}, fmt.Errorf("pipeline: ledger prompt: %w", promptErr)
			}
			if cancelled {
				return SortResult{}, nil // exit code 0 — user chose to cancel
			}
			// slw stays nil — processing continues without a ledger.
		} else {
			slw = manifest.NewSafeLedgerWriter(rawLW, out)
		}
	}

	// ------------------------------------------------------------------
	// 5. Process files (sequential or concurrent).
	// ------------------------------------------------------------------
	fmtr := NewFormatter(opts.ColorOutput)
	destLabel := opts.DestLabel
	var result SortResult
	if cfg.Workers > 1 {
		result = runConcurrentCtx(ctx, opts, discovered, skipped, fileIDs, dirA, dirB, out, slw, fmtr, destLabel)
	} else {
		result = runSequential(ctx, opts, discovered, skipped, fileIDs, dirA, dirB, out, slw, fmtr, destLabel)
	}

	// ------------------------------------------------------------------
	// 6. Finalise: close ledger, mark run complete in DB.
	// ------------------------------------------------------------------
	if err := slw.Close(); err != nil {
		_, _ = fmt.Fprintf(out, "WARNING: could not close ledger: %v\n", err)
	}
	if db != nil {
		if err := db.CompleteRun(opts.RunID, time.Now().UTC()); err != nil {
			_, _ = fmt.Fprintf(out, "WARNING: could not mark run complete: %v\n", err)
		}
	}

	_, _ = fmt.Fprintf(out, "\nDone. processed=%d duplicates=%d skipped=%d errors=%d\n",
		result.Processed, result.Duplicates, result.Skipped, result.Errors)
	_, _ = fmt.Fprintf(out, "(%s)\n", formatElapsed(time.Since(startedAt)))

	emit(opts.EventBus, progress.Event{
		Kind: progress.EventRunComplete,
		Summary: &progress.RunSummary{
			Processed:  result.Processed,
			Duplicates: result.Duplicates,
			Skipped:    result.Skipped,
			Errors:     result.Errors,
			Duration:   time.Since(startedAt),
		},
	})

	return result, nil
}

// runSequential processes all discovered files one at a time.
// ctx is checked between files; cancellation stops new work but does not
// interrupt a file that is already in progress.
func runSequential(ctx context.Context, opts SortOptions, discovered []discovery.DiscoveredFile,
	skipped []discovery.SkippedFile,
	fileIDs map[string]int64, dirA, dirB string, out io.Writer, lw *manifest.SafeLedgerWriter, fmtr *Formatter, destLabel string) SortResult {

	var result SortResult
	db := opts.DB
	// In-memory dedup fallback used when no DB is available (e.g. tests, dry-run without DB).
	// Maps checksum → relative destination of the first completed file.
	memSeen := make(map[string]string)

	cfg := opts.Config

	// --- Emit SKIP lines for discovery-phase skips (unsupported, dotfiles, etc.) ---
	for _, sf := range skipped {
		if cfg.Verbosity >= 0 {
			_, _ = fmt.Fprint(out, fmtr.FormatOutput("SKIP", sf.Path, sf.Reason))
		}
		lw.WriteEntry(domain.LedgerEntry{
			Path:   sf.Path,
			Status: domain.LedgerStatusSkip,
			Reason: sf.Reason,
		})
		// Insert a DB row for the skipped file (no fileID pre-allocated; insert directly).
		if db != nil {
			skipFileID, insertErr := db.InsertFile(&archivedb.FileRecord{
				RunID:      opts.RunID,
				SourcePath: filepath.Join(dirA, sf.Path),
			})
			if insertErr == nil {
				if dbErr := db.UpdateFileStatus(skipFileID, "skipped",
					archivedb.WithSkipReason(sf.Reason)); dbErr != nil {
					_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", sf.Path, dbErr)
				}
			}
		}
		result.Skipped++
		emit(opts.EventBus, progress.Event{
			Kind:      progress.EventFileSkipped,
			RelPath:   sf.Path,
			Reason:    sf.Reason,
			WorkerID:  -1,
			Completed: result.Skipped + result.Errors,
		})
	}

	for _, df := range discovered {
		// Stop accepting new files if the context has been cancelled (e.g. SIGINT).
		select {
		case <-ctx.Done():
			return result
		default:
		}

		fileID := fileIDs[df.Path]

		// --- Check if previously imported ---
		if db != nil {
			processed, checkErr := db.CheckSourceProcessed(df.Path)
			if checkErr != nil {
				if cfg.Verbosity >= 0 {
					_, _ = fmt.Fprint(out, fmtr.FormatOutput("ERR ", df.RelPath, checkErr.Error()))
				}
				result.Errors++
				emit(opts.EventBus, progress.Event{
					Kind:      progress.EventFileError,
					RelPath:   df.RelPath,
					Reason:    checkErr.Error(),
					Err:       checkErr,
					WorkerID:  -1,
					Completed: result.Skipped + result.Processed + result.Errors,
				})
				continue
			}
			if processed {
				const reason = "previously imported"
				if cfg.Verbosity >= 0 {
					_, _ = fmt.Fprint(out, fmtr.FormatOutput("SKIP", df.RelPath, reason))
				}
				lw.WriteEntry(domain.LedgerEntry{
					Path:   df.RelPath,
					Status: domain.LedgerStatusSkip,
					Reason: reason,
				})
				if dbErr := db.UpdateFileStatus(fileID, "skipped",
					archivedb.WithSkipReason(reason)); dbErr != nil {
					_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
				}
				result.Skipped++
				emit(opts.EventBus, progress.Event{
					Kind:      progress.EventFileSkipped,
					RelPath:   df.RelPath,
					Reason:    reason,
					WorkerID:  -1,
					Completed: result.Skipped + result.Processed + result.Errors,
				})
				continue
			}
		}

		var fileSize int64
		if fi, statErr := os.Stat(df.Path); statErr == nil {
			fileSize = fi.Size()
		}
		emit(opts.EventBus, progress.Event{
			Kind:     progress.EventFileStart,
			RelPath:  df.RelPath,
			WorkerID: -1,
			FileSize: fileSize,
		})

		fileStart := time.Now()
		le, isDup, err := processFile(df, fileID, opts, dirA, dirB, out, memSeen, fmtr, destLabel, fileSize)
		if err != nil {
			var dfs *dateFilterSkip
			if errors.As(err, &dfs) {
				// Date filter skip — not an error.
				if cfg.Verbosity >= 0 {
					_, _ = fmt.Fprint(out, fmtr.FormatOutput("SKIP", df.RelPath, dfs.reason))
					if cfg.Verbosity >= 1 {
						_, _ = fmt.Fprintf(out, "  (%s)\n", time.Since(fileStart).Truncate(time.Millisecond))
					}
				}
				lw.WriteEntry(domain.LedgerEntry{
					Path:   df.RelPath,
					Status: domain.LedgerStatusSkip,
					Reason: dfs.reason,
				})
				if db != nil {
					if dbErr := db.UpdateFileStatus(fileID, "skipped",
						archivedb.WithSkipReason(dfs.reason),
						archivedb.WithCaptureDate(dfs.captureDate)); dbErr != nil {
						_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
					}
				}
				result.Skipped++
				emit(opts.EventBus, progress.Event{
					Kind:      progress.EventFileSkipped,
					RelPath:   df.RelPath,
					Reason:    dfs.reason,
					WorkerID:  -1,
					Completed: result.Skipped + result.Processed + result.Errors,
				})
				continue
			}
			result.Errors++
			if db != nil {
				if dbErr := db.UpdateFileStatus(fileID, "failed", archivedb.WithError(err.Error())); dbErr != nil {
					_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
				}
			}
			if cfg.Verbosity >= 0 {
				_, _ = fmt.Fprint(out, fmtr.FormatOutput("ERR ", df.RelPath, err.Error()))
				if cfg.Verbosity >= 1 {
					_, _ = fmt.Fprintf(out, "  (%s)\n", time.Since(fileStart).Truncate(time.Millisecond))
				}
			}
			lw.WriteEntry(domain.LedgerEntry{
				Path:   df.RelPath,
				Status: domain.LedgerStatusError,
				Reason: err.Error(),
			})
			emit(opts.EventBus, progress.Event{
				Kind:      progress.EventFileError,
				RelPath:   df.RelPath,
				Reason:    err.Error(),
				Err:       err,
				WorkerID:  -1,
				Completed: result.Skipped + result.Processed + result.Errors,
			})
			continue
		}

		result.Processed++
		if cfg.Verbosity >= 1 {
			_, _ = fmt.Fprintf(out, "  (%s)\n", time.Since(fileStart).Truncate(time.Millisecond))
		}
		if isDup {
			result.Duplicates++
			emit(opts.EventBus, progress.Event{
				Kind:        progress.EventFileDuplicate,
				RelPath:     df.RelPath,
				IsDuplicate: true,
				MatchesDest: le.Matches,
				Destination: le.Destination,
				SidecarExts: sidecarExts(df.Sidecars, le.Sidecars),
				WorkerID:    -1,
				Completed:   result.Skipped + result.Processed + result.Errors,
			})
		} else {
			dest := ""
			var scExts []string
			if le != nil {
				dest = le.Destination
				scExts = sidecarExts(df.Sidecars, le.Sidecars)
			}
			emit(opts.EventBus, progress.Event{
				Kind:        progress.EventFileComplete,
				RelPath:     df.RelPath,
				Destination: dest,
				SidecarExts: scExts,
				WorkerID:    -1,
				Completed:   result.Skipped + result.Processed + result.Errors,
			})
		}
		if le != nil {
			// Record in memSeen so subsequent files with the same checksum are routed as duplicates.
			if db == nil {
				memSeen[le.Checksum] = le.Destination
			}
			lw.WriteEntry(*le)
		}
	}

	return result
}

// processFile runs the full pipeline for a single file and returns a
// LedgerEntry on success (nil on dry-run or duplicate without copy).
// isDuplicate is true when the file was routed to the duplicates directory.
// memSeen is an in-memory dedup map used when db is nil; it maps checksum → relDest.
// destLabel is the display prefix for destination paths (e.g. "...Photos"); see displayDest.
// fileSize is the source file size in bytes (from os.Stat), used for byte-level progress events.
func processFile(
	df discovery.DiscoveredFile,
	fileID int64,
	opts SortOptions,
	dirA, dirB string,
	out io.Writer,
	memSeen map[string]string,
	fmtr *Formatter,
	destLabel string,
	fileSize int64,
) (*domain.LedgerEntry, bool, error) {
	cfg := opts.Config
	db := opts.DB
	now := func() time.Time { return time.Now().UTC() }
	bus := opts.EventBus
	const workerID = -1 // sequential mode uses coordinator ID

	// --- Extract date ---
	captureDate, err := df.Handler.ExtractDate(df.Path)
	if err != nil {
		return nil, false, fmt.Errorf("extract date: %w", err)
	}
	if db != nil {
		_ = db.UpdateFileStatus(fileID, "extracted",
			archivedb.WithCaptureDate(captureDate))
	}
	emit(bus, progress.Event{
		Kind:        progress.EventFileExtracted,
		RelPath:     df.RelPath,
		CaptureDate: captureDate,
		WorkerID:    workerID,
	})

	// --- Date filter gate ---
	if cfg.Since != nil && captureDate.Before(*cfg.Since) {
		return nil, false, &dateFilterSkip{
			reason:      "outside date range: before " + cfg.Since.Format("2006-01-02"),
			captureDate: captureDate,
		}
	}
	if cfg.Before != nil && captureDate.After(*cfg.Before) {
		return nil, false, &dateFilterSkip{
			reason:      "outside date range: after " + cfg.Before.Truncate(24*time.Hour).Format("2006-01-02"),
			captureDate: captureDate,
		}
	}

	// --- Hash media payload ---
	rc, err := df.Handler.HashableReader(df.Path)
	if err != nil {
		return nil, false, fmt.Errorf("open hashable reader: %w", err)
	}
	// Wrap with ProgressReader for byte-level progress (no-op when bus is nil).
	hashReader := progress.NewProgressReader(rc, bus, df.RelPath, workerID, "HASH", fileSize)
	checksum, err := opts.Hasher.Sum(hashReader)
	_ = rc.Close()
	if err != nil {
		return nil, false, fmt.Errorf("hash payload: %w", err)
	}
	if db != nil {
		_ = db.UpdateFileStatus(fileID, "hashed",
			archivedb.WithChecksum(checksum),
			archivedb.WithAlgorithm(opts.Hasher.Algorithm()))
	}
	emit(bus, progress.Event{
		Kind:     progress.EventFileHashed,
		RelPath:  df.RelPath,
		Checksum: checksum,
		WorkerID: workerID,
	})

	// --- Dedup check ---
	var isDuplicate bool
	var existingDestForLedger string
	if db != nil {
		existingDest, err := db.CheckDuplicate(checksum)
		if err != nil {
			return nil, false, fmt.Errorf("dedup check: %w", err)
		}
		isDuplicate = existingDest != ""
		existingDestForLedger = existingDest
	} else if dest, seen := memSeen[checksum]; seen {
		isDuplicate = true
		existingDestForLedger = dest
	}

	// --- Skip duplicates (when --skip-duplicates is set) ---
	if isDuplicate && cfg.SkipDuplicates {
		if db != nil {
			if dbErr := db.UpdateFileStatus(fileID, "complete",
				archivedb.WithChecksum(checksum),
				archivedb.WithAlgorithm(opts.Hasher.Algorithm()),
				archivedb.WithIsDuplicate(true)); dbErr != nil {
				_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
			}
		}
		matchDetail := existingDestForLedger
		if cfg.Verbosity >= 0 {
			_, _ = fmt.Fprint(out, fmtr.FormatOutput("DUPE", df.RelPath,
				fmt.Sprintf("matches %s", displayDest(destLabel, matchDetail))))
		}
		le := &domain.LedgerEntry{
			Path:     df.RelPath,
			Status:   domain.LedgerStatusDuplicate,
			Checksum: checksum,
			Matches:  existingDestForLedger,
			// Destination intentionally omitted — no file was written.
		}
		return le, true, nil
	}

	// --- Build destination path ---
	ext := filepath.Ext(df.Path)
	relDest := pathbuilder.Build(opts.PathTemplate, captureDate, opts.Hasher.AlgorithmID(), checksum, ext, isDuplicate, opts.RunTimestamp)
	absDest := filepath.Join(dirB, relDest)

	if cfg.DryRun {
		if cfg.Verbosity >= 0 {
			// Build sidecar annotation from associated sidecars (no files copied in dry-run).
			var dryAnnotation string
			if cfg.CarrySidecars && len(df.Sidecars) > 0 {
				var exts []string
				for _, sc := range df.Sidecars {
					exts = append(exts, sc.Ext)
				}
				dryAnnotation = formatSidecarAnnotation(exts)
			}
			_, _ = fmt.Fprintf(out, "  DRY-RUN  %s -> %s%s\n", df.RelPath, displayDest(destLabel, relDest), dryAnnotation)
		}
		if db != nil {
			if dbErr := db.UpdateFileStatus(fileID, "complete",
				archivedb.WithDestination(absDest, relDest),
				archivedb.WithIsDuplicate(isDuplicate)); dbErr != nil {
				_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
			}
		}
		if isDuplicate {
			le := &domain.LedgerEntry{
				Path:        df.RelPath,
				Status:      domain.LedgerStatusDuplicate,
				Checksum:    checksum,
				Destination: relDest,
				Matches:     existingDestForLedger,
			}
			return le, true, nil
		}
		return nil, false, nil
	}

	// --- Copy (atomic: write to temp file) ---
	// Wrap the destination writer with ProgressWriter for byte-level progress.
	copyWriter := progress.NewProgressWriter(nil, bus, df.RelPath, workerID, "COPY", fileSize)
	tmpPath, err := copypkg.ExecuteWithProgress(df.Path, absDest, func(w io.Writer) io.Writer {
		copyWriter = progress.NewProgressWriter(w, bus, df.RelPath, workerID, "COPY", fileSize)
		return copyWriter
	})
	if err != nil {
		return nil, false, fmt.Errorf("copy: %w", err)
	}
	// Emit a final 100% byte-progress event so the UI sees completion before
	// the stage-transition EventFileCopied arrives.
	copyWriter.EmitFinal()
	if db != nil {
		// Record the intended final destination; the temp path is an
		// implementation detail not tracked in the DB.
		_ = db.UpdateFileStatus(fileID, "copied",
			archivedb.WithDestination(absDest, relDest))
	}
	emit(bus, progress.Event{
		Kind:        progress.EventFileCopied,
		RelPath:     df.RelPath,
		Destination: relDest,
		WorkerID:    workerID,
	})

	// --- Verify (hash the temp file) ---
	// Wrap the hashable reader with ProgressReader for byte-level progress.
	vr := copypkg.VerifyWithProgress(tmpPath, checksum, df.Handler, opts.Hasher, func(r io.Reader) io.Reader {
		return progress.NewProgressReader(r, bus, df.RelPath, workerID, "VERIFY", fileSize)
	})
	if !vr.Success {
		copypkg.CleanupTempFile(tmpPath)
		if db != nil {
			if dbErr := db.UpdateFileStatus(fileID, "mismatch", archivedb.WithError(vr.Error.Error())); dbErr != nil {
				_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
			}
		}
		return nil, false, fmt.Errorf("verify: %w", vr.Error)
	}

	// --- Promote (atomic rename temp → canonical path) ---
	if err := copypkg.Promote(tmpPath, absDest); err != nil {
		copypkg.CleanupTempFile(tmpPath)
		if db != nil {
			if dbErr := db.UpdateFileStatus(fileID, "failed", archivedb.WithError(err.Error())); dbErr != nil {
				_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
			}
		}
		return nil, false, fmt.Errorf("promote: %w", err)
	}
	verifiedAt := now()
	if db != nil {
		_ = db.UpdateFileStatus(fileID, "verified")
	}
	emit(bus, progress.Event{
		Kind:        progress.EventFileVerified,
		RelPath:     df.RelPath,
		Destination: relDest,
		WorkerID:    workerID,
	})

	// --- Carry sidecars (after verify, before tag) ---
	var carriedSidecarRels []string // dest_rel paths of successfully carried sidecars
	var carriedXMPAbs string        // absolute dest path of carried .xmp (for tag merge)
	if cfg.CarrySidecars && len(df.Sidecars) > 0 {
		for _, sc := range df.Sidecars {
			sidecarDest := absDest + sc.Ext
			sidecarRel := relDest + sc.Ext
			if err := copypkg.CopySidecar(sc.Path, sidecarDest); err != nil {
				if cfg.Verbosity >= 0 {
					_, _ = fmt.Fprint(out, fmtr.FormatWarning(fmt.Sprintf("sidecar carry failed for %s: %v", sc.RelPath, err)))
				}
				emit(bus, progress.Event{
					Kind:           progress.EventSidecarFailed,
					RelPath:        df.RelPath,
					SidecarRelPath: sc.RelPath,
					SidecarExt:     sc.Ext,
					Reason:         err.Error(),
					Err:            err,
					WorkerID:       workerID,
				})
				continue
			}
			carriedSidecarRels = append(carriedSidecarRels, sidecarRel)
			emit(bus, progress.Event{
				Kind:           progress.EventSidecarCarried,
				RelPath:        df.RelPath,
				SidecarRelPath: sc.RelPath,
				SidecarExt:     sc.Ext,
				Destination:    sidecarRel,
				WorkerID:       workerID,
			})
			if sc.Ext == ".xmp" {
				carriedXMPAbs = sidecarDest
			}
		}
	}

	// --- Tag (optional) ---
	tags := resolveTags(cfg, captureDate)
	if !tags.IsEmpty() {
		if err := tagging.ApplyWithSidecars(absDest, df.Handler, tags, carriedXMPAbs, cfg.OverwriteSidecarTags); err != nil {
			if db != nil {
				if dbErr := db.UpdateFileStatus(fileID, "tag_failed", archivedb.WithError(err.Error())); dbErr != nil {
					_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
				}
			}
			if cfg.Verbosity >= 0 {
				_, _ = fmt.Fprint(out, fmtr.FormatWarning(fmt.Sprintf("tag failed for %s: %v", df.RelPath, err)))
			}
			// Tag failure is non-fatal: file is copied and verified.
		} else {
			if db != nil {
				_ = db.UpdateFileStatus(fileID, "tagged")
			}
			emit(bus, progress.Event{
				Kind:     progress.EventFileTagged,
				RelPath:  df.RelPath,
				WorkerID: workerID,
			})
		}
	}

	// --- Complete (atomic dedup re-check) ---
	if db != nil {
		if isDuplicate {
			// Pre-copy dedup already determined this is a duplicate.
			// No race check needed — just mark complete.
			if dbErr := db.UpdateFileStatus(fileID, "complete",
				archivedb.WithIsDuplicate(true),
				archivedb.WithCarriedSidecars(carriedSidecarRels)); dbErr != nil {
				_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
			}
		} else {
			// Atomically check for a cross-process race: another pixe process may
			// have completed the same checksum while we were copying.
			existingDest, dedupErr := db.CompleteFileWithDedupCheck(fileID, checksum)
			if dedupErr != nil {
				return nil, false, fmt.Errorf("complete with dedup check: %w", dedupErr)
			}
			if existingDest != "" {
				// Race detected: another process completed this checksum first.
				// Relocate our copy to the duplicates directory.
				dupRelDest := pathbuilder.Build(opts.PathTemplate, captureDate, opts.Hasher.AlgorithmID(), checksum, ext, true, opts.RunTimestamp)
				dupAbsDest := filepath.Join(dirB, dupRelDest)
				if renErr := os.Rename(absDest, dupAbsDest); renErr != nil {
					// Rename failed — file is still at absDest; mark as failed.
					if dbErr := db.UpdateFileStatus(fileID, "failed", archivedb.WithError(renErr.Error())); dbErr != nil {
						_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
					}
					return nil, false, fmt.Errorf("relocate duplicate after race: %w", renErr)
				}
				// Update DB record with the new duplicate destination.
				if dbErr := db.UpdateFileStatus(fileID, "complete",
					archivedb.WithDestination(dupAbsDest, dupRelDest),
					archivedb.WithIsDuplicate(true),
					archivedb.WithCarriedSidecars(carriedSidecarRels)); dbErr != nil {
					_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
				}
				relDest = dupRelDest
				isDuplicate = true
				existingDestForLedger = existingDest
			} else {
				// Non-race path: CompleteFileWithDedupCheck set status='complete'.
				// Update carried_sidecars if any were carried.
				if len(carriedSidecarRels) > 0 {
					if dbErr := db.UpdateFileStatus(fileID, "complete",
						archivedb.WithCarriedSidecars(carriedSidecarRels)); dbErr != nil {
						_, _ = fmt.Fprintf(out, "WARNING: DB status update failed for %q: %v\n", df.RelPath, dbErr)
					}
				}
			}
		}
	}

	// --- Emit output line after outcome is known ---
	annotation := formatSidecarAnnotation(sidecarExts(df.Sidecars, carriedSidecarRels))
	if cfg.Verbosity >= 0 {
		if isDuplicate {
			matchDetail := existingDestForLedger
			if matchDetail == "" {
				matchDetail = relDest
			}
			_, _ = fmt.Fprint(out, fmtr.FormatOutputWithAnnotation("DUPE", df.RelPath,
				fmt.Sprintf("matches %s", displayDest(destLabel, matchDetail)), annotation))
		} else {
			_, _ = fmt.Fprint(out, fmtr.FormatOutputWithAnnotation("COPY", df.RelPath, displayDest(destLabel, relDest), annotation))
		}
	}

	// Build ledger entry.
	if isDuplicate {
		le := &domain.LedgerEntry{
			Path:        df.RelPath,
			Status:      domain.LedgerStatusDuplicate,
			Checksum:    checksum,
			Destination: relDest,
			Sidecars:    carriedSidecarRels,
			Matches:     existingDestForLedger,
		}
		return le, true, nil
	}

	le := &domain.LedgerEntry{
		Path:        df.RelPath,
		Status:      domain.LedgerStatusCopy,
		Checksum:    checksum,
		Destination: relDest,
		VerifiedAt:  &verifiedAt,
		Sidecars:    carriedSidecarRels,
	}
	return le, false, nil
}

// formatElapsed formats a time.Duration as a compact human-readable string
// for the sort summary line (e.g. "1m 23s", "45s", "0.8s").
func formatElapsed(d time.Duration) string {
	if d < time.Second {
		return fmt.Sprintf("%.1fs", d.Seconds())
	}
	total := int(d.Seconds())
	h := total / 3600
	m := (total % 3600) / 60
	s := total % 60
	switch {
	case h > 0:
		return fmt.Sprintf("%dh %dm %ds", h, m, s)
	case m > 0:
		return fmt.Sprintf("%dm %ds", m, s)
	default:
		return fmt.Sprintf("%ds", s)
	}
}

// handleLedgerFailure handles the case where the ledger cannot be created.
// It prompts the user interactively when appropriate, or auto-accepts based on
// the --yes and --no-ledger flags and stdin TTY detection.
//
// Returns (cancelled=true, nil) when the user chose to cancel.
// Returns (cancelled=false, nil) when processing should continue without a ledger.
// Returns (false, err) on an unexpected I/O error reading stdin.
func handleLedgerFailure(out io.Writer, dirA string, lwErr error, yes, noLedger bool) (cancelled bool, err error) {
	if noLedger {
		// Explicit opt-out — no warning, no prompt.
		return false, nil
	}

	// Always print the warning.
	_, _ = fmt.Fprintf(out, "Warning: cannot create ledger in %s: %v\n", dirA, lwErr)

	if yes || !isatty.IsTerminal(os.Stdin.Fd()) {
		// Auto-accept (--yes flag) or non-interactive stdin (CI, pipes, cron).
		// Print warning and continue.
		return false, nil
	}

	// Interactive prompt.
	_, _ = fmt.Fprintf(out, "Without a ledger, this source directory will have no record of which files were sorted.\n")
	_, _ = fmt.Fprintf(out, "Continue without ledger? [y/N] ")

	reader := bufio.NewReader(os.Stdin)
	line, readErr := reader.ReadString('\n')
	if readErr != nil && readErr != io.EOF {
		return false, readErr
	}
	answer := strings.TrimSpace(line)
	if !isYesAnswer(answer) {
		_, _ = fmt.Fprintln(out, "Cancelled.")
		return true, nil
	}
	return false, nil
}

// isYesAnswer reports whether the user's answer is an affirmative response.
func isYesAnswer(s string) bool {
	lower := strings.ToLower(strings.TrimSpace(s))
	return lower == "y" || lower == "yes"
}

// resolveTags renders the Copyright placeholder and returns a MetadataTags value.
func resolveTags(cfg *config.AppConfig, captureDate time.Time) domain.MetadataTags {
	tags := domain.MetadataTags{
		CameraOwner: cfg.CameraOwner,
	}
	if cfg.CopyrightTemplate != nil {
		tags.Copyright = tagging.RenderCopyright(cfg.CopyrightTemplate, captureDate)
	}
	return tags
}
