// Copyright 2026 Chris Wells <chris@rhza.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package pipeline implements the sort orchestrator that wires together
// discovery, extraction, hashing, path building, copy, verify, tagging,
// and archive-DB / ledger persistence.
//
// State is persisted to the SQLite archive database (archivedb). The ledger
// (dirA/.pixe_ledger.json) is written in JSONL format via manifest.LedgerWriter:
// the coordinator goroutine streams one JSON line per file as each result is
// finalised, keeping memory usage O(1) regardless of file count.
package pipeline

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/cwlls/pixe-go/internal/archivedb"
	"github.com/cwlls/pixe-go/internal/config"
	copypkg "github.com/cwlls/pixe-go/internal/copy"
	"github.com/cwlls/pixe-go/internal/discovery"
	"github.com/cwlls/pixe-go/internal/domain"
	"github.com/cwlls/pixe-go/internal/hash"
	"github.com/cwlls/pixe-go/internal/ignore"
	"github.com/cwlls/pixe-go/internal/manifest"
	"github.com/cwlls/pixe-go/internal/pathbuilder"
	"github.com/cwlls/pixe-go/internal/progress"
	"github.com/cwlls/pixe-go/internal/tagging"
)

// SortOptions holds the resolved runtime options for a sort run.
// It is constructed by the CLI layer and passed into Run.
type SortOptions struct {
	// Config is the resolved application configuration.
	Config *config.AppConfig
	// Hasher computes content checksums for deduplication and verification.
	Hasher *hash.Hasher
	// Registry maps file extensions to their FileTypeHandler implementations.
	Registry *discovery.Registry
	// RunTimestamp is the formatted timestamp for this run, used in duplicate directory naming (e.g., "20260306_103000").
	RunTimestamp string
	// Output is where progress lines are written. Defaults to os.Stdout.
	Output io.Writer
	// PixeVersion is the version string stamped into ledgers.
	// Set by the CLI layer via cmd.Version() to avoid an import cycle.
	PixeVersion string
	// DB is the open archive database. Required for all non-dry-run operations.
	DB *archivedb.DB
	// RunID is the UUID for this run, pre-generated by the caller.
	RunID string
	// EventBus, when non-nil, receives structured progress events alongside
	// the plain-text Output writer. Both can be active simultaneously.
	// When nil, no events are emitted (existing behaviour is unchanged).
	EventBus *progress.Bus
}

// emit sends an event to the bus if one is configured. It is a no-op when
// bus is nil, so callers do not need to guard every call site.
func emit(bus *progress.Bus, e progress.Event) {
	if bus != nil {
		bus.Emit(e)
	}
}

// SortResult summarises the outcome of a completed sort run.
type SortResult struct {
	Processed  int // Processed is the total number of files that completed the pipeline.
	Duplicates int // Duplicates is the number of files identified as content duplicates.
	Skipped    int // Skipped is the number of files skipped (previously imported or unsupported).
	Errors     int // Errors is the number of files that failed at some pipeline stage.
}

// formatOutput returns a single stdout line for a file outcome.
// verb is one of "COPY", "SKIP", "DUPE", "ERR ".
// source is the relative path from dirA (displayed on the left).
// detail is the destination path or reason (displayed on the right).
func formatOutput(verb, source, detail string) string {
	return fmt.Sprintf("%s %s -> %s\n", verb, source, detail)
}

// Run executes the full sort pipeline, selecting sequential or concurrent
// execution based on opts.Config.Workers.
//
// Pipeline per file:
//
//	discover → extract date → hash payload → dedup check → build path
//	→ copy → verify → tag (optional) → update DB → update ledger
//
// After all files: write ledger to dirA, mark run complete in DB.
// In dry-run mode the copy/verify/tag steps are skipped; everything else runs.
func Run(opts SortOptions) (SortResult, error) {
	out := opts.Output
	if out == nil {
		out = os.Stdout
	}

	cfg := opts.Config
	dirA := cfg.Source
	dirB := cfg.Destination
	db := opts.DB

	startedAt := time.Now().UTC()

	// ------------------------------------------------------------------
	// 1. Register this run in the archive DB.
	// ------------------------------------------------------------------
	run := &archivedb.Run{
		ID:          opts.RunID,
		PixeVersion: opts.PixeVersion,
		Source:      dirA,
		Destination: dirB,
		Algorithm:   opts.Hasher.Algorithm(),
		Workers:     cfg.Workers,
		Recursive:   cfg.Recursive,
		StartedAt:   startedAt,
	}
	if db != nil {
		if err := db.InsertRun(run); err != nil {
			return SortResult{}, fmt.Errorf("pipeline: insert run: %w", err)
		}
	}

	// ------------------------------------------------------------------
	// 2. Walk dirA.
	// ------------------------------------------------------------------
	walkOpts := discovery.WalkOptions{
		Recursive:     cfg.Recursive,
		Ignore:        ignore.New(cfg.Ignore),
		CarrySidecars: cfg.CarrySidecars,
	}
	discovered, skipped, err := discovery.Walk(dirA, opts.Registry, walkOpts)
	if err != nil {
		return SortResult{}, fmt.Errorf("pipeline: walk source: %w", err)
	}
	emit(opts.EventBus, progress.Event{
		Kind:    progress.EventDiscoverDone,
		Total:   len(discovered),
		Skipped: len(skipped),
	})

	// ------------------------------------------------------------------
	// 3. Batch-insert all discovered files as "pending".
	// ------------------------------------------------------------------
	// fileIDs maps source path → DB file ID.
	fileIDs := make(map[string]int64, len(discovered))
	if db != nil && len(discovered) > 0 {
		records := make([]*archivedb.FileRecord, len(discovered))
		for i, df := range discovered {
			records[i] = &archivedb.FileRecord{
				RunID:      opts.RunID,
				SourcePath: df.Path,
			}
		}
		ids, err := db.InsertFiles(records)
		if err != nil {
			return SortResult{}, fmt.Errorf("pipeline: batch insert files: %w", err)
		}
		for i, df := range discovered {
			fileIDs[df.Path] = ids[i]
		}
	}

	// ------------------------------------------------------------------
	// 4. Open streaming ledger writer (nil in dry-run — no ledger written).
	// ------------------------------------------------------------------
	var slw *manifest.SafeLedgerWriter
	if !cfg.DryRun {
		header := domain.LedgerHeader{
			Version:     4,
			RunID:       opts.RunID,
			PixeVersion: opts.PixeVersion,
			PixeRun:     startedAt.UTC().Format(time.RFC3339),
			Algorithm:   opts.Hasher.Algorithm(),
			Destination: dirB,
			Recursive:   cfg.Recursive,
		}
		rawLW, lwErr := manifest.NewLedgerWriter(dirA, header)
		if lwErr != nil {
			_, _ = fmt.Fprintf(out, "WARNING: could not open ledger in %s: %v\n", dirA, lwErr)
			// slw stays nil — processing continues without a ledger.
		} else {
			slw = manifest.NewSafeLedgerWriter(rawLW, out)
		}
	}

	// ------------------------------------------------------------------
	// 5. Process files (sequential or concurrent).
	// ------------------------------------------------------------------
	var result SortResult
	if cfg.Workers > 1 {
		result = RunConcurrent(opts, discovered, skipped, fileIDs, dirA, dirB, out, slw)
	} else {
		result = runSequential(opts, discovered, skipped, fileIDs, dirA, dirB, out, slw)
	}

	// ------------------------------------------------------------------
	// 6. Finalise: close ledger, mark run complete in DB.
	// ------------------------------------------------------------------
	if err := slw.Close(); err != nil {
		_, _ = fmt.Fprintf(out, "WARNING: could not close ledger: %v\n", err)
	}
	if db != nil {
		if err := db.CompleteRun(opts.RunID, time.Now().UTC()); err != nil {
			_, _ = fmt.Fprintf(out, "WARNING: could not mark run complete: %v\n", err)
		}
	}

	_, _ = fmt.Fprintf(out, "\nDone. processed=%d duplicates=%d skipped=%d errors=%d\n",
		result.Processed, result.Duplicates, result.Skipped, result.Errors)

	emit(opts.EventBus, progress.Event{
		Kind: progress.EventRunComplete,
		Summary: &progress.RunSummary{
			Processed:  result.Processed,
			Duplicates: result.Duplicates,
			Skipped:    result.Skipped,
			Errors:     result.Errors,
			Duration:   time.Since(startedAt),
		},
	})

	return result, nil
}

// runSequential processes all discovered files one at a time.
func runSequential(opts SortOptions, discovered []discovery.DiscoveredFile,
	skipped []discovery.SkippedFile,
	fileIDs map[string]int64, dirA, dirB string, out io.Writer, lw *manifest.SafeLedgerWriter) SortResult {

	var result SortResult
	db := opts.DB
	// In-memory dedup fallback used when no DB is available (e.g. tests, dry-run without DB).
	// Maps checksum → relative destination of the first completed file.
	memSeen := make(map[string]string)

	// --- Emit SKIP lines for discovery-phase skips (unsupported, dotfiles, etc.) ---
	for _, sf := range skipped {
		_, _ = fmt.Fprint(out, formatOutput("SKIP", sf.Path, sf.Reason))
		lw.WriteEntry(domain.LedgerEntry{
			Path:   sf.Path,
			Status: domain.LedgerStatusSkip,
			Reason: sf.Reason,
		})
		// Insert a DB row for the skipped file (no fileID pre-allocated; insert directly).
		if db != nil {
			skipFileID, insertErr := db.InsertFile(&archivedb.FileRecord{
				RunID:      opts.RunID,
				SourcePath: filepath.Join(dirA, sf.Path),
			})
			if insertErr == nil {
				_ = db.UpdateFileStatus(skipFileID, "skipped",
					archivedb.WithSkipReason(sf.Reason))
			}
		}
		result.Skipped++
		emit(opts.EventBus, progress.Event{
			Kind:      progress.EventFileSkipped,
			RelPath:   sf.Path,
			Reason:    sf.Reason,
			WorkerID:  -1,
			Completed: result.Skipped + result.Errors,
		})
	}

	for _, df := range discovered {
		fileID := fileIDs[df.Path]

		// --- Check if previously imported ---
		if db != nil {
			processed, checkErr := db.CheckSourceProcessed(df.Path)
			if checkErr != nil {
				_, _ = fmt.Fprint(out, formatOutput("ERR ", df.RelPath, checkErr.Error()))
				result.Errors++
				emit(opts.EventBus, progress.Event{
					Kind:      progress.EventFileError,
					RelPath:   df.RelPath,
					Reason:    checkErr.Error(),
					Err:       checkErr,
					WorkerID:  -1,
					Completed: result.Skipped + result.Processed + result.Errors,
				})
				continue
			}
			if processed {
				const reason = "previously imported"
				_, _ = fmt.Fprint(out, formatOutput("SKIP", df.RelPath, reason))
				lw.WriteEntry(domain.LedgerEntry{
					Path:   df.RelPath,
					Status: domain.LedgerStatusSkip,
					Reason: reason,
				})
				_ = db.UpdateFileStatus(fileID, "skipped",
					archivedb.WithSkipReason(reason))
				result.Skipped++
				emit(opts.EventBus, progress.Event{
					Kind:      progress.EventFileSkipped,
					RelPath:   df.RelPath,
					Reason:    reason,
					WorkerID:  -1,
					Completed: result.Skipped + result.Processed + result.Errors,
				})
				continue
			}
		}

		emit(opts.EventBus, progress.Event{
			Kind:     progress.EventFileStart,
			RelPath:  df.RelPath,
			WorkerID: -1,
		})

		le, isDup, err := processFile(df, fileID, opts, dirA, dirB, out, memSeen)
		if err != nil {
			result.Errors++
			if db != nil {
				_ = db.UpdateFileStatus(fileID, "failed", archivedb.WithError(err.Error()))
			}
			_, _ = fmt.Fprint(out, formatOutput("ERR ", df.RelPath, err.Error()))
			lw.WriteEntry(domain.LedgerEntry{
				Path:   df.RelPath,
				Status: domain.LedgerStatusError,
				Reason: err.Error(),
			})
			emit(opts.EventBus, progress.Event{
				Kind:      progress.EventFileError,
				RelPath:   df.RelPath,
				Reason:    err.Error(),
				Err:       err,
				WorkerID:  -1,
				Completed: result.Skipped + result.Processed + result.Errors,
			})
			continue
		}

		result.Processed++
		if isDup {
			result.Duplicates++
			emit(opts.EventBus, progress.Event{
				Kind:        progress.EventFileDuplicate,
				RelPath:     df.RelPath,
				IsDuplicate: true,
				MatchesDest: le.Matches,
				Destination: le.Destination,
				WorkerID:    -1,
				Completed:   result.Skipped + result.Processed + result.Errors,
			})
		} else {
			dest := ""
			if le != nil {
				dest = le.Destination
			}
			emit(opts.EventBus, progress.Event{
				Kind:        progress.EventFileComplete,
				RelPath:     df.RelPath,
				Destination: dest,
				WorkerID:    -1,
				Completed:   result.Skipped + result.Processed + result.Errors,
			})
		}
		if le != nil {
			// Record in memSeen so subsequent files with the same checksum are routed as duplicates.
			if db == nil {
				memSeen[le.Checksum] = le.Destination
			}
			lw.WriteEntry(*le)
		}
	}

	return result
}

// processFile runs the full pipeline for a single file and returns a
// LedgerEntry on success (nil on dry-run or duplicate without copy).
// isDuplicate is true when the file was routed to the duplicates directory.
// memSeen is an in-memory dedup map used when db is nil; it maps checksum → relDest.
func processFile(
	df discovery.DiscoveredFile,
	fileID int64,
	opts SortOptions,
	dirA, dirB string,
	out io.Writer,
	memSeen map[string]string,
) (*domain.LedgerEntry, bool, error) {
	cfg := opts.Config
	db := opts.DB
	now := func() time.Time { return time.Now().UTC() }

	// --- Extract date ---
	captureDate, err := df.Handler.ExtractDate(df.Path)
	if err != nil {
		return nil, false, fmt.Errorf("extract date: %w", err)
	}
	if db != nil {
		_ = db.UpdateFileStatus(fileID, "extracted",
			archivedb.WithCaptureDate(captureDate))
	}
	emit(opts.EventBus, progress.Event{
		Kind:        progress.EventFileExtracted,
		RelPath:     df.RelPath,
		CaptureDate: captureDate,
		WorkerID:    -1,
	})

	// --- Hash media payload ---
	rc, err := df.Handler.HashableReader(df.Path)
	if err != nil {
		return nil, false, fmt.Errorf("open hashable reader: %w", err)
	}
	checksum, err := opts.Hasher.Sum(rc)
	_ = rc.Close()
	if err != nil {
		return nil, false, fmt.Errorf("hash payload: %w", err)
	}
	if db != nil {
		_ = db.UpdateFileStatus(fileID, "hashed", archivedb.WithChecksum(checksum))
	}
	emit(opts.EventBus, progress.Event{
		Kind:     progress.EventFileHashed,
		RelPath:  df.RelPath,
		Checksum: checksum,
		WorkerID: -1,
	})

	// --- Dedup check ---
	var isDuplicate bool
	var existingDestForLedger string
	if db != nil {
		existingDest, err := db.CheckDuplicate(checksum)
		if err != nil {
			return nil, false, fmt.Errorf("dedup check: %w", err)
		}
		isDuplicate = existingDest != ""
		existingDestForLedger = existingDest
	} else if dest, seen := memSeen[checksum]; seen {
		isDuplicate = true
		existingDestForLedger = dest
	}

	// --- Skip duplicates (when --skip-duplicates is set) ---
	if isDuplicate && cfg.SkipDuplicates {
		if db != nil {
			_ = db.UpdateFileStatus(fileID, "complete",
				archivedb.WithChecksum(checksum),
				archivedb.WithIsDuplicate(true))
		}
		matchDetail := existingDestForLedger
		_, _ = fmt.Fprint(out, formatOutput("DUPE", df.RelPath,
			fmt.Sprintf("matches %s", matchDetail)))
		le := &domain.LedgerEntry{
			Path:     df.RelPath,
			Status:   domain.LedgerStatusDuplicate,
			Checksum: checksum,
			Matches:  existingDestForLedger,
			// Destination intentionally omitted — no file was written.
		}
		return le, true, nil
	}

	// --- Build destination path ---
	ext := filepath.Ext(df.Path)
	relDest := pathbuilder.Build(captureDate, checksum, ext, isDuplicate, opts.RunTimestamp)
	absDest := filepath.Join(dirB, relDest)

	if cfg.DryRun {
		_, _ = fmt.Fprintf(out, "  DRY-RUN  %s -> %s\n", df.RelPath, relDest)
		// Emit sidecar association lines even in dry-run (no files copied).
		dryTags := resolveTags(cfg, captureDate)
		emitSidecarLines(out, df.Sidecars, relDest, dryTags, cfg)
		if db != nil {
			_ = db.UpdateFileStatus(fileID, "complete",
				archivedb.WithDestination(absDest, relDest),
				archivedb.WithIsDuplicate(isDuplicate))
		}
		if isDuplicate {
			le := &domain.LedgerEntry{
				Path:        df.RelPath,
				Status:      domain.LedgerStatusDuplicate,
				Checksum:    checksum,
				Destination: relDest,
				Matches:     existingDestForLedger,
			}
			return le, true, nil
		}
		return nil, false, nil
	}

	// --- Copy (atomic: write to temp file) ---
	tmpPath, err := copypkg.Execute(df.Path, absDest)
	if err != nil {
		return nil, false, fmt.Errorf("copy: %w", err)
	}
	if db != nil {
		// Record the intended final destination; the temp path is an
		// implementation detail not tracked in the DB.
		_ = db.UpdateFileStatus(fileID, "copied",
			archivedb.WithDestination(absDest, relDest))
	}
	emit(opts.EventBus, progress.Event{
		Kind:        progress.EventFileCopied,
		RelPath:     df.RelPath,
		Destination: relDest,
		WorkerID:    -1,
	})

	// --- Verify (hash the temp file) ---
	vr := copypkg.Verify(tmpPath, checksum, df.Handler, opts.Hasher)
	if !vr.Success {
		copypkg.CleanupTempFile(tmpPath)
		if db != nil {
			_ = db.UpdateFileStatus(fileID, "mismatch", archivedb.WithError(vr.Error.Error()))
		}
		return nil, false, fmt.Errorf("verify: %w", vr.Error)
	}

	// --- Promote (atomic rename temp → canonical path) ---
	if err := copypkg.Promote(tmpPath, absDest); err != nil {
		copypkg.CleanupTempFile(tmpPath)
		if db != nil {
			_ = db.UpdateFileStatus(fileID, "failed", archivedb.WithError(err.Error()))
		}
		return nil, false, fmt.Errorf("promote: %w", err)
	}
	verifiedAt := now()
	if db != nil {
		_ = db.UpdateFileStatus(fileID, "verified")
	}
	emit(opts.EventBus, progress.Event{
		Kind:        progress.EventFileVerified,
		RelPath:     df.RelPath,
		Destination: relDest,
		WorkerID:    -1,
	})

	// --- Carry sidecars (after verify, before tag) ---
	var carriedSidecarRels []string // dest_rel paths of successfully carried sidecars
	var carriedXMPAbs string        // absolute dest path of carried .xmp (for tag merge)
	if cfg.CarrySidecars && len(df.Sidecars) > 0 {
		for _, sc := range df.Sidecars {
			sidecarDest := absDest + sc.Ext
			sidecarRel := relDest + sc.Ext
			if err := copypkg.CopySidecar(sc.Path, sidecarDest); err != nil {
				_, _ = fmt.Fprintf(out, "  WARNING  sidecar carry failed for %s: %v\n", sc.RelPath, err)
				emit(opts.EventBus, progress.Event{
					Kind:           progress.EventSidecarFailed,
					RelPath:        df.RelPath,
					SidecarRelPath: sc.RelPath,
					SidecarExt:     sc.Ext,
					Reason:         err.Error(),
					Err:            err,
					WorkerID:       -1,
				})
				continue
			}
			carriedSidecarRels = append(carriedSidecarRels, sidecarRel)
			emit(opts.EventBus, progress.Event{
				Kind:           progress.EventSidecarCarried,
				RelPath:        df.RelPath,
				SidecarRelPath: sc.RelPath,
				SidecarExt:     sc.Ext,
				Destination:    sidecarRel,
				WorkerID:       -1,
			})
			if sc.Ext == ".xmp" {
				carriedXMPAbs = sidecarDest
			}
		}
	}

	// --- Tag (optional) ---
	tags := resolveTags(cfg, captureDate)
	if !tags.IsEmpty() {
		if err := tagging.ApplyWithSidecars(absDest, df.Handler, tags, carriedXMPAbs, cfg.OverwriteSidecarTags); err != nil {
			if db != nil {
				_ = db.UpdateFileStatus(fileID, "tag_failed", archivedb.WithError(err.Error()))
			}
			_, _ = fmt.Fprintf(out, "  WARNING  tag failed for %s: %v\n", df.RelPath, err)
			// Tag failure is non-fatal: file is copied and verified.
		} else {
			if db != nil {
				_ = db.UpdateFileStatus(fileID, "tagged")
			}
			emit(opts.EventBus, progress.Event{
				Kind:     progress.EventFileTagged,
				RelPath:  df.RelPath,
				WorkerID: -1,
			})
		}
	}

	// --- Complete (atomic dedup re-check) ---
	if db != nil {
		if isDuplicate {
			// Pre-copy dedup already determined this is a duplicate.
			// No race check needed — just mark complete.
			_ = db.UpdateFileStatus(fileID, "complete",
				archivedb.WithIsDuplicate(true),
				archivedb.WithCarriedSidecars(carriedSidecarRels))
		} else {
			// Atomically check for a cross-process race: another pixe process may
			// have completed the same checksum while we were copying.
			existingDest, dedupErr := db.CompleteFileWithDedupCheck(fileID, checksum)
			if dedupErr != nil {
				return nil, false, fmt.Errorf("complete with dedup check: %w", dedupErr)
			}
			if existingDest != "" {
				// Race detected: another process completed this checksum first.
				// Relocate our copy to the duplicates directory.
				dupRelDest := pathbuilder.Build(captureDate, checksum, ext, true, opts.RunTimestamp)
				dupAbsDest := filepath.Join(dirB, dupRelDest)
				if renErr := os.Rename(absDest, dupAbsDest); renErr != nil {
					// Rename failed — file is still at absDest; mark as failed.
					_ = db.UpdateFileStatus(fileID, "failed", archivedb.WithError(renErr.Error()))
					return nil, false, fmt.Errorf("relocate duplicate after race: %w", renErr)
				}
				// Update DB record with the new duplicate destination.
				_ = db.UpdateFileStatus(fileID, "complete",
					archivedb.WithDestination(dupAbsDest, dupRelDest),
					archivedb.WithIsDuplicate(true),
					archivedb.WithCarriedSidecars(carriedSidecarRels))
				relDest = dupRelDest
				isDuplicate = true
				existingDestForLedger = existingDest
			} else {
				// Non-race path: CompleteFileWithDedupCheck set status='complete'.
				// Update carried_sidecars if any were carried.
				if len(carriedSidecarRels) > 0 {
					_ = db.UpdateFileStatus(fileID, "complete",
						archivedb.WithCarriedSidecars(carriedSidecarRels))
				}
			}
		}
	}

	// --- Emit output line after outcome is known ---
	if isDuplicate {
		matchDetail := existingDestForLedger
		if matchDetail == "" {
			matchDetail = relDest
		}
		_, _ = fmt.Fprint(out, formatOutput("DUPE", df.RelPath,
			fmt.Sprintf("matches %s", matchDetail)))
		emitSidecarLines(out, df.Sidecars, relDest, tags, cfg)
	} else {
		_, _ = fmt.Fprint(out, formatOutput("COPY", df.RelPath, relDest))
		emitSidecarLines(out, df.Sidecars, relDest, tags, cfg)
	}

	// Build ledger entry.
	if isDuplicate {
		le := &domain.LedgerEntry{
			Path:        df.RelPath,
			Status:      domain.LedgerStatusDuplicate,
			Checksum:    checksum,
			Destination: relDest,
			Sidecars:    carriedSidecarRels,
			Matches:     existingDestForLedger,
		}
		return le, true, nil
	}

	le := &domain.LedgerEntry{
		Path:        df.RelPath,
		Status:      domain.LedgerStatusCopy,
		Checksum:    checksum,
		Destination: relDest,
		VerifiedAt:  &verifiedAt,
		Sidecars:    carriedSidecarRels,
	}
	return le, false, nil
}

// emitSidecarLines writes +sidecar output lines for each sidecar associated
// with a discovered file. Called after the parent COPY/DUPE line is emitted.
func emitSidecarLines(out io.Writer, sidecars []discovery.SidecarFile, parentRelDest string, tags domain.MetadataTags, cfg *config.AppConfig) {
	if !cfg.CarrySidecars || len(sidecars) == 0 {
		return
	}
	for _, sc := range sidecars {
		sidecarRel := parentRelDest + sc.Ext
		suffix := ""
		if sc.Ext == ".xmp" && !tags.IsEmpty() {
			suffix = " (merge tags)"
		}
		_, _ = fmt.Fprintf(out, "     +sidecar %s -> %s%s\n", sc.RelPath, sidecarRel, suffix)
	}
}

// resolveTags renders the Copyright placeholder and returns a MetadataTags value.
func resolveTags(cfg *config.AppConfig, captureDate time.Time) domain.MetadataTags {
	tags := domain.MetadataTags{
		CameraOwner: cfg.CameraOwner,
	}
	if cfg.Copyright != "" {
		tags.Copyright = tagging.RenderCopyright(cfg.Copyright, captureDate)
	}
	return tags
}
