theme: jekyll-theme-slate
title: Pixe
description: Safe, deterministic photo and video sorting
url: "https://cwlls.github.io"
baseurl: "/pixe"
# <!-- pixe:begin:version -->
version: "v2.6.1"
# <!-- pixe:end:version -->
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
